###check registration
POST http://localhost:3500/register
Content-Type: application/json  

{
    "user": "Bien Chimano",
    "pwd": "sautisol"
}

###check login
POST http://localhost:3500/auth
Content-Type: application/json  

{
    "user": "Tony Mwailengo",
    "pwd": "riperbi"
}

###check refresh token
GET http://localhost:3500/refresh
content-type: application/json
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRvbnkgTXdhaWxlbmdvIiwiaWF0IjoxNzYxMTk4OTMxLCJleHAiOjE3NjEyODUzMzF9.q-FFE_oyRowodV5PI9TX6ihAlRAoEaFFYxFypOV-yPw

###check logout
GET http://localhost:3500/logout
content-type: application/json
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRvbnkgTXdhaWxlbmdvIiwiaWF0IjoxNzYxMTk4OTMxLCJleHAiOjE3NjEyODUzMzF9.q-FFE_oyRowodV5PI9TX6ihAlRAoEaFFYxFypOV-yPw