###get all employees
GET http://localhost:3500/employees
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJ1c2VybmFtZSI6IlRvbnkgTXdhaWxlbmdvIiwicm9sZXMiOlsyMDAxLG51bGwsNTE1MF19LCJpYXQiOjE3NjExOTg5MzEsImV4cCI6MTc2MTE5OTA1MX0.WNeVOJc6nV4jKT1YosSW01DVFG0ntCtKOBhwZltE1QM

###create new employee
POST http://localhost:3500/employees
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJ1c2VybmFtZSI6IlRvbnkgTXdhaWxlbmdvIiwicm9sZXMiOlsyMDAxLG51bGwsNTE1MF19LCJpYXQiOjE3NjExOTkwNzcsImV4cCI6MTc2MTE5OTE5N30.GsXukVAPdgvfbQ62nPPMmLPFEudsr5LNcDCg0d_Ow4Y  
Content-Type: application/json

{
    "firstname": "Joseph",
    "lastname": "kilambe"
}

###update employee
PUT http://localhost:3500/employees 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJ1c2VybmFtZSI6IlRvbnkgTXdhaWxlbmdvIiwicm9sZXMiOlsyMDAxLG51bGwsNTE1MF19LCJpYXQiOjE3NjExOTkwNzcsImV4cCI6MTc2MTE5OTE5N30.GsXukVAPdgvfbQ62nPPMmLPFEudsr5LNcDCg0d_Ow4Y
Content-Type: application/json 

{
    "firstname": "Amri",
    "lastname": "hare"
}

###delete employee
DELETE http://localhost:3500/employees
Content-Type: application/json  
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJ1c2VybmFtZSI6IlRvbnkgTXdhaWxlbmdvIiwicm9sZXMiOlsyMDAxLG51bGwsNTE1MF19LCJpYXQiOjE3NjExOTkwNzcsImV4cCI6MTc2MTE5OTE5N30.GsXukVAPdgvfbQ62nPPMmLPFEudsr5LNcDCg0d_Ow4Y

{
    "id": "68f71b371fa4cea54d972c8d"
}

###get employee by id
GET http://localhost:3500/employees/3
Content-Type: application/json  
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJ1c2VybmFtZSI6IlRvbnkgTXdhaWxlbmdvIiwicm9sZXMiOlsyMDAxLG51bGwsNTE1MF19LCJpYXQiOjE3NjExOTkwNzcsImV4cCI6MTc2MTE5OTE5N30.GsXukVAPdgvfbQ62nPPMmLPFEudsr5LNcDCg0d_Ow4Y

{
    "id": "68f71b371fa4cea54d972c8d"
}

###add role
PUT http://localhost:3500/roleAssignment
content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJ1c2VybmFtZSI6IlRvbnkgTXdhaWxlbmdvIiwicm9sZXMiOlsyMDAxLG51bGwsNTE1MF19LCJpYXQiOjE3NjEyMTQyOTEsImV4cCI6MTc2MTIxNDQxMX0.TTKMCSLcweV-_4hTsPNkKnm2fbbTZNLBPvmZq2WHP6o


{
    "username": "Bien Chimano",
    "id": "68d38f137381acd486af32fb",
    "roleName": "Admin" 
}

###remove role
DELETE http://localhost:3500/roleAssignment
content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJ1c2VybmFtZSI6IlRvbnkgTXdhaWxlbmdvIiwicm9sZXMiOlsyMDAxLG51bGwsNTE1MF19LCJpYXQiOjE3NjEyMTU5NzYsImV4cCI6MTc2MTIxNjA5Nn0.95FqqOXqvsKTIuCiWp_S6ESU2aEAuO5LEANhfY7oAOQ

{
    "username": "Bien Chimano", 
    "id": "68d38f137381acd486af32fb",
    "roleName": "Admin" 
}   